# Generated by Django 5.1.7 on 2025-03-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logincredentials',
            old_name='username',
            new_name='email',
        ),
    ]
