# Generated by Django 5.1.7 on 2025-03-16 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_backend', '0003_registrationcredentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationCredentials',
        ),
    ]
